### ISSUE TITLE
wen prod

### ISSUE THREAD

**Issue by skylenet** [binaryedge/docs.binaryedge.io#32]
Hi sir. I wantz to know wen prod. Thx. :eyes:

**Comment by balgan** [comment]
ASSIGNING TICKET TO DEV. PROD SOON.

**Comment by skylenet** [comment]
PROD FIRST. DEV SECOND. LET'S MAKE PROD GREAT AGAIN.

**Comment by balgan** [comment]
NO REAL PROBLEM. CLOSING.

**Comment by skylenet** [comment]
NO CODE. NO PROBLEM!

**Comment by skylenet** [comment]
Disclaimer: This was a joke. No developer was hurt by creating this issue.
